spring:
  application.name: INTERVIEW
  datasource:
    url: jdbc:h2:mem:interview_db
    username: user
    password: Passw0rd
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect